/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockRouteImport } from './routes/stock'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LivraisonsRouteImport } from './routes/livraisons'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExportRouteImport } from './routes/export'
import { Route as CoffretsRouteImport } from './routes/coffrets'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ArchivesRouteImport } from './routes/archives'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LivraisonsIdRouteImport } from './routes/livraisons.$id'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalCguRouteImport } from './routes/legal/cgu'

const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LivraisonsRoute = LivraisonsRouteImport.update({
  id: '/livraisons',
  path: '/livraisons',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCguRoute = LegalCguRouteImport.update({
  id: '/legal/cgu',
  path: '/legal/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const CoffretsRoute = CoffretsRouteImport.update({
  id: '/coffrets',
  path: '/coffrets',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivesRoute = ArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivraisonsIdRoute = LivraisonsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LivraisonsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archives': typeof ArchivesRoute
  '/clients': typeof ClientsRoute
  '/coffrets': typeof CoffretsRoute
  '/export': typeof ExportRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/livraisons': typeof LivraisonsRouteWithChildren
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stock': typeof StockRoute
  '/livraisons/$id': typeof LivraisonsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archives': typeof ArchivesRoute
  '/clients': typeof ClientsRoute
  '/coffrets': typeof CoffretsRoute
  '/export': typeof ExportRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/livraisons': typeof LivraisonsRouteWithChildren
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stock': typeof StockRoute
  '/livraisons/$id': typeof LivraisonsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archives': typeof ArchivesRoute
  '/clients': typeof ClientsRoute
  '/coffrets': typeof CoffretsRoute
  '/export': typeof ExportRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/livraisons': typeof LivraisonsRouteWithChildren
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stock': typeof StockRoute
  '/livraisons/$id': typeof LivraisonsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archives'
    | '/clients'
    | '/coffrets'
    | '/export'
    | '/forgot-password'
    | '/legal/cgu'
    | '/legal/privacy'
    | '/livraisons'
    | '/login'
    | '/production'
    | '/reset-password'
    | '/stock'
    | '/livraisons/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archives'
    | '/clients'
    | '/coffrets'
    | '/export'
    | '/forgot-password'
    | '/legal/cgu'
    | '/legal/privacy'
    | '/livraisons'
    | '/login'
    | '/production'
    | '/reset-password'
    | '/stock'
    | '/livraisons/$id'
  id:
    | '__root__'
    | '/'
    | '/archives'
    | '/clients'
    | '/coffrets'
    | '/export'
    | '/forgot-password'
    | '/legal/cgu'
    | '/legal/privacy'
    | '/livraisons'
    | '/login'
    | '/production'
    | '/reset-password'
    | '/stock'
    | '/livraisons/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivesRoute: typeof ArchivesRoute
  ClientsRoute: typeof ClientsRoute
  CoffretsRoute: typeof CoffretsRoute
  ExportRoute: typeof ExportRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LegalCguRoute: typeof LegalCguRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LivraisonsRoute: typeof LivraisonsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProductionRoute: typeof ProductionRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StockRoute: typeof StockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livraisons': {
      id: '/livraisons'
      path: '/livraisons'
      fullPath: '/livraisons'
      preLoaderRoute: typeof LivraisonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cgu': {
      id: '/legal/cgu'
      path: '/legal/cgu'
      fullPath: '/legal/cgu'
      preLoaderRoute: typeof LegalCguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coffrets': {
      id: '/coffrets'
      path: '/coffrets'
      fullPath: '/coffrets'
      preLoaderRoute: typeof CoffretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archives': {
      id: '/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof ArchivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livraisons/$id': {
      id: '/livraisons/$id'
      path: '/$id'
      fullPath: '/livraisons/$id'
      preLoaderRoute: typeof LivraisonsIdRouteImport
      parentRoute: typeof LivraisonsRoute
    }
  }
}

interface LivraisonsRouteChildren {
  LivraisonsIdRoute: typeof LivraisonsIdRoute
}

const LivraisonsRouteChildren: LivraisonsRouteChildren = {
  LivraisonsIdRoute: LivraisonsIdRoute,
}

const LivraisonsRouteWithChildren = LivraisonsRoute._addFileChildren(
  LivraisonsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivesRoute: ArchivesRoute,
  ClientsRoute: ClientsRoute,
  CoffretsRoute: CoffretsRoute,
  ExportRoute: ExportRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LegalCguRoute: LegalCguRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LivraisonsRoute: LivraisonsRouteWithChildren,
  LoginRoute: LoginRoute,
  ProductionRoute: ProductionRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StockRoute: StockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
